import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//export default function RootLayout({ children }) {
//  return (
//    <html lang="en">
//      <body
//        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//      >
//        {children}
//      </body>
//    </html>
//  );
//}

// src/app/layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Barra de navegación */}
        <nav className="p-4 bg-gray-200 flex gap-4">
          <a href="/login" className="underline">
            Login
          </a>
          <a href="/register" className="underline">
            Registro
          </a>
          <a href="/tasks" className="underline">
            Tareas
          </a>
        </nav>

        {/* Contenido principal */}
        {children}
      </body>
    </html>
  );
}

